### ISSUE TITLE
Timeline blank slice is not a function error when viewing

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7392] opened 2021-03-23 02:08 UTC
## 💡 Summary

TypeError: (intermediate value).slice is not a function

## 🙂 Expected Behavior

No error

## ☹️ Actual Behavior

Can deleting all old notes before upgrade cause this or just coincidence?
Error with empty timeline

![misskeyslice](https://user-images.githubusercontent.com/1679025/112081943-e2018500-8b5a-11eb-9495-5670a8edacae.png)

## 📝 Steps to Reproduce

1. Deleted all old notes from 12.74 (not sure if related to this)
2. Upgrade to Misskey 12.75
3. View timeline after upgrade
4. Error message

## 📌 Environment

Misskey 12.75.0 PostgreSQL 10.15

**Comment by syuilo** [comment] 2021-03-23 06:21
投稿に含まれるURLを処理する過程で発生しているようだが、再現は出来ない

**Comment by Johann150** [comment] 2022-03-30 15:48
closing this because it is outdated and was not reproducible

**Closed as completed by Johann150** 2022-03-30 15:48 UTC
Labels: ⚠️bug?
