### ISSUE TITLE
timeline mention error and timed out

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#7586] opened 2021-06-24 21:58 UTC
## 💡 Summary

timeline mention error and timed out

## 🙂 Expected Behavior

mentions are displayed for each user

## ☹️ Actual Behavior

load icon spinning and error message is displayed

## 📝 Steps to Reproduce

1. login 
2. click on timeline
3. click mention icon

## 📌 Environment

misskey 12.83.0 - node 12.22.1 - postgresql v10.17

**Comment by cliqsocial** [comment] 2021-06-24 22:00
This is what we are getting from our account:
![misskey-timeline-mentions](https://user-images.githubusercontent.com/60059665/123337824-cfaa3500-d515-11eb-9ae3-d0a57f024287.png)

![misskey-timeline-mention-error](https://user-images.githubusercontent.com/60059665/123337945-fa948900-d515-11eb-90e7-a4c15c024680.png)

User reported the issue to us and @syuilo here: 
https://cliq.social/notes/8nekev2tad

**Comment by RaZZlom** [comment] 2021-06-26 08:47
What in Logs?

**Comment by Johann150** [comment] 2022-02-06 22:26
Duplicate of #7632

**Closed as completed by Johann150** 2022-02-06 22:26 UTC
