### ISSUE TITLE
Post Button is Not a Circle

### ISSUE THREAD

**Issue by Co2333** [misskey-dev/misskey#8051] opened 2021-12-12 05:20 UTC
48x54 🥺

Misskey - 12.98.0
Node.js - v16.6.2
Vue - 3.2.21

<img width="277" alt="截屏2021-12-12 下午1 17 34" src="https://user-images.githubusercontent.com/25259084/145701325-fb9163af-bec9-4f20-a91a-649f2ee83179.png">

**Comment by Johann150** [comment] 2021-12-12 20:28
duplicate of #8049

**Closed** 2021-12-14 09:13 UTC
Labels: 🐛Bug, 🖥️Client
