### ISSUE TITLE
authorize-follow takes forever to load for some users

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3663] opened 2018-12-18 15:46 UTC
# Summary
authorize-follow takes forever to load for some users, the loading bar goes slow and eventually stops at the end

# Expected Behavior
Allow me to follow the user

# Actual Behavior
Loads forever

# Steps to Reproduce
1. Remote-follow phoronix@bot.undernet.uy or DeeUnderscore@cathoderay.tube

# Environment

firefox, macos

**Comment by mei23** [comment] 2018-12-18 17:59
The first one seem to GNU social.
Misskey can't comunicate with GNU social. (No common protocol implimented.)

The second one ...
Sorry, I do not know.

**Comment by zyoshoka** [comment] 2024-06-12 09:55
Problems with following GNU social users was addressed in #9019. The reproduction procedure mentioned is no longer reproducible due to the server closure, so closing this issue.

**Closed as completed by zyoshoka** 2024-06-12 09:55 UTC
