### ISSUE TITLE
Search results only appear when scroll to top

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#7200] opened 2021-02-15 04:09 UTC
## 💡 Summary

-If user is not aware, the search results appear to be blank.
-User requires browser scroll to the top

reference: https://cliq.social/notes/8i8xgumm50

## 🙂 Expected Behavior

Browser start at top to show search results

## ☹️ Actual Behavior

Require user to scroll to top to see results

## 📝 Steps to Reproduce

1. view timeline
2. use search
3. scroll to the top for results

## 📌 Environment

nginx 1.19.6 - node 12.20.1 - npm 6.14.10 - misskey 12.69.0

**Comment by Johann150** [comment] 2021-08-21 18:30
duplicate of #6790

**Comment by Johann150** [comment] 2022-02-06 22:55
Duplicate of #6790

**Closed as completed by Johann150** 2022-02-06 22:55 UTC
Labels: ⚠️bug?
