### ISSUE TITLE
Quoted renote and remote renote interaction

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3405] opened 2018-11-25 21:47 UTC
When using misskeys quoted renote feature, would it be possible to let the remote instance (ex. mastodon) know that the post has been renoted? So that in the remote instance 
![image](https://user-images.githubusercontent.com/2098066/48985052-058ba080-f104-11e8-8b25-adbae21685cd.png) will be +1?

**Comment by Johann150** [comment] 2022-02-07 16:40
duplicate of #2264

**Closed as completed by Johann150** 2022-02-07 16:40 UTC
