### ISSUE TITLE
Misskey breaks URLs containing non-latin characters

### ISSUE THREAD

**Issue by Ai-rin** [misskey-dev/misskey#7416] opened 2021-03-28 19:29 UTC
Example: only first one will work in Misskey.

https://en.wikipedia.org/wiki/Anime
https://uk.wikipedia.org/wiki/Аніме
https://ja.wikipedia.org/wiki/アニメ

![Screenshot_20210328_222409](https://user-images.githubusercontent.com/29887769/112765117-571a0200-9014-11eb-8c9f-faaaf016cec8.png)

## 📌 Environment
Misskey v12.75.1

**Comment by syuilo** [comment] 2021-03-29 00:02
This is (currently) in design. Please use correct URLs.

**Comment by KawaneRio** [comment] 2021-03-29 00:11
Alternatively, you can use angle brackets`<>` to specify a non-Latin URL. This functionality exists in *Github Markdown* as well as *MFM*.

https://co.misskey.io/notes/8jxef1hsxp
> ```
> <https://en.wikipedia.org/wiki/Anime>
> <https://uk.wikipedia.org/wiki/Аніме>
> <https://ja.wikipedia.org/wiki/アニメ>
> ```
> <https://en.wikipedia.org/wiki/Anime>
> <https://uk.wikipedia.org/wiki/Аніме>
> <https://ja.wikipedia.org/wiki/アニメ>

**Comment by Ai-rin** [comment] 2021-04-19 12:38
The `<URL>` method was great, but stopped to work currently (v12.77.0)
Regression?
![Screenshot_20210419_152949](https://user-images.githubusercontent.com/29887769/115237038-c02cfb00-a124-11eb-9104-b29e9ffa935b.png)

**Comment by norz** [comment] 2021-08-11 19:54
**Workaround tip for iOS** : in Safari, use the share menu then "copy". You should get an encoded url that will work, e.g.: https://fr.wikipedia.org/wiki/Brebis_%C3%A9gar%C3%A9e

**Comment by marihachi** [comment] 2021-12-11 13:03
まだこの問題が残ってますかね

**Comment by Johann150** [comment] 2022-06-01 18:41
Duplicate of https://github.com/misskey-dev/mfm.js/issues/98

**Closed as not planned by Johann150** 2022-06-01 18:41 UTC
Labels: ⚠️bug?
