### ISSUE TITLE
Save Emoji Locally

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3738] opened 2018-12-24 04:50 UTC
# Summary

It would be great if misskey downloaded and saved added emoji locally, that way there would be no worry about the source going down, file being deleted etc.
This would also improve both performance and security on the user end, as there would be no outward requests to other potentially dangerous sites.

**Comment by tamaina** [comment] 2018-12-24 06:02
How about using browser cache?

**Comment by ibrokemypie** [comment] 2018-12-24 06:08
That would help somewhat, but the emoji still need to *exist* on the remote end, and it only *reduces* the number of requests made in certain occasions. If the emoji were instead downloaded server side the same way remote avatars are downloaded, and stored entirely by the instance, this would stop any problems from occurring.

**Comment by tamaina** [comment] 2018-12-24 09:05
Oh, is there a proposal to cache on the server side? (Then the same as #3214?)

**Comment by ibrokemypie** [comment] 2018-12-24 09:19
ah yes, I guess so, though I would see it less as a cache as that implies that it still relies on the remote server, and more as simply serving local copies.

**Comment by rinsuki** [comment] 2020-07-17 00:09
Duplicate of #3214

**Closed as completed by rinsuki** 2020-07-17 00:09 UTC
