### ISSUE TITLE
Opening Notes in new Tab impossible (shows blank page with "Not Found" text)

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6542] opened 2020-07-12 18:39 UTC
すみません、私の日本語はまだ足りない、だから英語でせつめいします。
質問があれば、日本語で答えてがんばります（でももしかしてむりです）

## 💡 Summary

I am not sure when this bug started appearing. It could be after Misskey v12.40.0 or after v12.40.1. The issue is that opening a Note in a new Tab does not work anymore. Specifically, you are shown a "Not Found" message. This is not because the Note has been deleted, as you can access the Note if you open it directly, in the same tab. For example if you have a Tab open on the Misskey Home Timeline and then click on a note to open its details, it will display properly. But if you select to open the details of a note in a new tab, you will be shown the "Not Found" error. This happens for local and remote notes (so both from Misskey.io and e.g. mstdn.jp). The "Not Found" screen is also not a prepared "Not Found" screen from Misskey, but a completely blank page that only shows the words "Not Found".

This means that you cannot send links to notes to your friends or similar.

## 🙂 Expected Behavior

The Note should be properly displayed like it was in previous versions, instead of showing a "Not Found" screen.

## ☹️ Actual Behavior

As described in the summary. If you open a note (local or remote) in a new tab, you are shown a blank page with only the words "Not Found". Images below.

## 📝 Steps to Reproduce

1. Go to Misskey Home Timeline
2. Find a note and open it in a new tab
3. You are shown a blank page with only "Not Found" text

## 📌 Environment

Instance: Misskey.io
Version: v12.41.1
Browser: All (Serverside bug)

Example: 
![2020-07-12_20-34-03](https://user-images.githubusercontent.com/8159402/87254001-81746100-c47f-11ea-8a42-cf399356d2cd.gif)

**Comment by rinsuki** [comment] 2020-07-12 20:47
Duplicate of #6533 , and fixed at 12.41.2.

**Comment by robflop** [comment] 2020-07-12 20:48
Thank you and sorry for the duplicate!

**Comment by rinsuki** [comment] 2020-07-12 20:49
no problem ;-)

**Closed as completed** 2020-07-12 20:48 UTC
