### ISSUE TITLE
Missing strings (English)

### ISSUE THREAD

**Issue by RaZZlom** [misskey-dev/misskey#7411] opened 2021-03-27 11:05 UTC
## 💡 Summary

Some strings miss in English language.

1. Instance - Settings - Basic Info
2. Instance - Settings - Proxy Account
3. Instance - Federation - Sort
4. Instance - Reports - State

Screenshots

1. ![1](https://user-images.githubusercontent.com/73530026/112718562-e9cb7b80-8f04-11eb-9dce-ecf0d7bc81d7.png)
2. ![2](https://user-images.githubusercontent.com/73530026/112718570-f18b2000-8f04-11eb-8eb2-175148cb7ef8.png)
3. ![3](https://user-images.githubusercontent.com/73530026/112718573-f8b22e00-8f04-11eb-8f80-8af4eaa295f5.png)
4. ![4](https://user-images.githubusercontent.com/73530026/112718575-01a2ff80-8f05-11eb-85d0-6134c39a172e.png)

## 🙂 Expected Behavior

See text

## ☹️ Actual Behavior

No text

## 📝 Steps to Reproduce

1. Set English language
2. Open Instance - Settings - Basic Info
3. Open Instance - Settings - Proxy Account
4. Open Instance - Federation - Sort
5. Open Instance - Reports - State

## 📌 Environment

Misskey - v12.75.1
Node.js - v14.16.0
PostgreSQL - v13.2 (Debian 13.2-1.pgdg100+1)
Redis - v5.0.3

**Comment by robflop** [comment] 2021-08-21 15:06
（日本語の概要は下にある）

Problem (3) affects all languages, not just english (even japanese). The cause lies in the Code referencing localization strings that don't actually exist (maybe did in the past, but do not now). 

The relevant code for this can be found here:

https://github.com/misskey-dev/misskey/blob/fa49427df0ca9fd3ec5878a64cb4e1a4e40bf0f5/src/client/pages/federation.vue#L21-L38

As you can see, it references $ts.pubSub, $ts.caughtAt, $ts.lastCommunicatedAt amongst others, but the named three strings do not exist in the localization files:

https://github.com/misskey-dev/misskey/blob/develop/locales/ja-JP.yml

----------

問題③は存在しないi18nストリングの問題、だから全ての言語は影響されている（ja-JPも）。以上に埋め込んだコードに使った $ts.pubSub, $ts.caughtAt と $ts.lastCommunicatedAt はi18nファイルに存在しないだからスクショのような空になる。

**Comment by Johann150** [comment] 2021-08-21 15:17
I think (1) and (2) were solved already, right?
#7674 should fix (3) and now also (4)

**Comment by Johann150** [comment] 2021-09-04 19:05
should be fixed now

**Comment by tamaina** [comment] 2021-09-11 05:56
should be fixed now

**Comment by tamaina** [comment] 2021-09-11 14:40
ん？閉じ忘れか

**Closed as completed by tamaina** 2021-09-11 14:40 UTC
Labels: ⚠️bug?
