### ISSUE TITLE
isCat is not federating

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7227] opened 2021-02-18 16:19 UTC
## Summary

isCat not federating, i can't see cat ears in non-misskey accounts:
![noava](https://user-images.githubusercontent.com/41872648/108386201-5798cf00-7204-11eb-88db-680653fb27da.png)
Original instance:
![ava](https://user-images.githubusercontent.com/41872648/108386210-59629280-7204-11eb-8646-ad3841f4eabf.png)

But remote users using pleroma can see mine:
![myears](https://user-images.githubusercontent.com/41872648/108386527-a21a4b80-7204-11eb-8544-7047b30e1bad.png)

## Expected Behavior

Cat ears on remote non-misskey accounts

## Environment

Raspberry Pi 4B (armv7l)
PostgreSQL - 13.1
Node.js - 14.15.4
Redis - 6.0.9
Misskey - 12.69.0

**Comment by Craftplacer** [comment] 2021-03-24 05:14
I assume those two Pleroma instances are running [absturztaube's catify mod](https://git.pleroma.social/absturztaube/pleroma-mod-catify). If it's the case, then this is simply not a federation issue, because this is a *client-side* mod applied by the instance owners.

Pleroma doesn't have profile metadata for "being a cat" (unlike Misskey), therefore it doesn't federate like Misskey.

You can check whether your instance has that mod under "Settings":
![image](https://user-images.githubusercontent.com/22963120/112259104-fc755480-8c67-11eb-950e-f21bfaee7bc1.png)

One possible workaround is that Misskey adds those checks done by the catify mod for non-Misskey instances. Although I am not sure if that's something everyone wants.

**Comment by absturztau-be** [comment] 2021-05-18 12:08
> One possible workaround is that Misskey adds those checks done by the catify mod for non-Misskey instances. Although I am not sure if that's something everyone wants.

Honestly no. the right way about this would be that the mod would actually use the isCat flag to determine who is a cat und who's not

**Comment by Johann150** [comment] 2022-05-05 09:14
Since this is not a bug in Misskey, I'll close this.

**Closed as completed by Johann150** 2022-05-05 09:14 UTC
