### ISSUE TITLE
Note preview in Notifications does not have a string to translate how many files a note has

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6279] opened 2020-04-19 08:55 UTC
## 💡 Summary

In the notifications view, you are shown a preview of the Note a notification is about (e.g. when someone reacts to your note or replies to it). If said Note also has a file attached to it,there will be a notice in this notification along the lines of "(1 file attached)". However, this is not translated and there is no string in Crowdin to translate it either, so it always shows up in japanese (e.g. "(1つのファイル)").

## 🙂 Expected Behavior

There should be a string in Crowdin to translate this file amount indicator in the preview.

## ☹️ Actual Behavior

There is no such string in Crowdin.

## 📝 Steps to Reproduce

1. Switch to any language other than Japanese
2. Look at your notifications and find a note with file attachments
3. See that the notice about how many files are attached is still in japanese

![ShareX_2020-04-19_10-55-46](https://user-images.githubusercontent.com/8159402/79683739-55549580-822c-11ea-9265-ee5fa06db64d.png)

## 📌 Environment

Misskey v12.35.0-io
All browsers

**Comment by tamaina** [comment] 2020-05-01 09:05
最新版（v12.36.1-io）では直っていますか？

**Comment by robflop** [comment] 2020-05-01 10:50
![vivaldi_2020-05-01_12-48-17](https://user-images.githubusercontent.com/8159402/80800566-0e5e8c80-8baa-11ea-9853-46c27bf70c82.png)

No, not fixed yet.

**Comment by tamaina** [comment] 2020-05-01 10:56
確かに直ってないですね

**Comment by tamaina** [comment] 2020-05-13 13:46
Duplicate of #3100

**Closed as completed by tamaina** 2020-05-13 13:46 UTC
Labels: packages/frontend, i18n
