### ISSUE TITLE
Blank Page When Browsing With Firefox

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6430] opened 2020-06-01 17:16 UTC
## 💡 Summary

When visiting 12.38.1 site using Firefox it shows blank page

## 🙂 Expected Behavior

Normal site loading

## ☹️ Actual Behavior

Blank page with Firefox

InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

## 📝 Steps to Reproduce

1. Open Private Firefox window
2. Visit site that is 12.38.1
3. Blank page
4. Visit site that is 12.38.0
5. Page load with no problem

## 📌 Environment

Misskey 12.38.1 and Firefox
@syuilo note that it works with 12.38.0

**Comment by rinsuki** [comment] 2020-06-02 02:19
duplicate of #6420 

workaround: Use without private window OR use other browsers (like Chrome series)

**Closed as completed by rinsuki** 2020-06-02 02:19 UTC
Labels: ⚠️bug?
