### ISSUE TITLE
Self-XSSの警告のi18nが動いていない

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#3685] opened 2018-12-19 15:20 UTC
![image](https://user-images.githubusercontent.com/14953122/50229161-022ac280-03ed-11e9-9ae9-a40a7f53c4e7.png)

**Comment by syuilo** [comment] 2018-12-19 15:21
Duplicate of #3345
Thanks anyway!

**Closed as completed by syuilo** 2018-12-19 15:21 UTC
