### ISSUE TITLE
Thumbnail created for each hashtag in post

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5794] opened 2020-01-31 02:12 UTC
## 💡 Summary

When viewing a pixelfed post, thumbnail shows for each hashtag

This is what it looks like
![pixelfed-hashtag](https://user-images.githubusercontent.com/60059665/73506878-f728cb00-4411-11ea-830b-2d2d01df5898.jpg)

## 🙂 Expected Behavior

display post as normal 

## ☹️ Actual Behavior

thumbnail generated for each hashtag

## 📝 Steps to Reproduce

1. click on search
2. enter url for any pixelfed post containing hashtag
3. view will show thumbnail for each hashtag (see photo above)

## 📌 Environment
seeing this on both firefox and chrome

**Comment by mei23** [comment] 2020-01-31 02:15
Probably a duplicate of #5729, and fixed in the develop branch.

**Comment by cliqsocial** [comment] 2020-01-31 02:30
@mei23 yes duplicate sorry thanks

**Closed as completed** 2020-01-31 04:23 UTC
Labels: ⚠️bug?
