### ISSUE TITLE
Delete a user completely

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7090] opened 2021-01-15 07:25 UTC
## Summary
Allow to delete a user completely.

For example on my instance I have 83 users but only 12 active accounts all the others are spam bots, even if suspended and mutated these are still counted by the instance in the number of users, then it greatly inhibits the list of users on the admin page.

**Comment by tamaina** [comment] 2021-09-06 06:45
Duplicate of #7735

I give priority to #7735 due to the ongoing discussion.

**Closed as completed by tamaina** 2021-09-06 06:45 UTC
Labels: ✨Feature
