### ISSUE TITLE
Image Zooming in picture view

### ISSUE THREAD

**Issue by Dolany** [misskey-dev/misskey#7010] opened 2020-12-23 14:22 UTC
## Summary

When viewing a picture in timeline at misskey, if the picture is large enough, I can't see any details on it(especially via mobile).Because of that, I hope to add a Zoom Button that can help me adjust the size myself.
Thank you very much!

**Comment by Johann150** [comment] 2021-11-12 13:39
has been solved, duplicate of #7696

**Closed as completed** 2021-11-14 06:41 UTC
Labels: ✨Feature
