### ISSUE TITLE
Misskey breaks in firefox private/incognito windows

### ISSUE THREAD

**Issue by clarjon1** [misskey-dev/misskey#6780] opened 2020-10-29 18:28 UTC
## 💡 Summary

Misskey posts do not load in Firefox Private Tabs/windows, and shows an infinite loading symbol and an error in error console.

## 🙂 Expected Behavior

Misskey should load the post, like it does in a Chrome/Chromium incognito tab/window

## ☹️ Actual Behavior

A spinner icon is displayed, and the "Busy" mouse cursor is displayed when mousing over. Inspect element shows this error:

![image](https://user-images.githubusercontent.com/627845/97616092-7889aa00-19f2-11eb-9046-eddf864288ae.png)

## 📝 Steps to Reproduce

1. Open a Private/incognito window in Firefox
2. Go to a misskey instance url, for example: https://reconnected.cat6.network/notes/8dyojm0oxz
3. Observe the infinite spinning loading icon, and the error shown in the error console.

## 📌 Environment

Tested with:

Misskey
v12.51.0

Firefox 82 on windows and linux

**Comment by rinsuki** [comment] 2020-10-29 20:28
duplicate of #6420

**Closed as completed by rinsuki** 2020-10-29 20:28 UTC
Labels: ⚠️bug?
